kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30064
    targetPort: 80
  type: NodePort
